tap 'bytemarkhosting/tools'
tap 'homebrew/dupes'

brew 'ansible'
brew 'autoconf'
brew 'automake'
brew 'axel'
brew 'bazaar'
brew 'caddy'
brew 'coreutils'
brew 'docbook'
brew 'ffmpeg'
brew 'gnu-sed'
brew 'gnupg2'
brew 'go'
brew 'gnutls'
brew 'httpie'
brew 'gpg-agent'
brew 'graphviz'
brew 'hugo'
brew 'imagemagick'
brew 'ipcalc'
brew 'jo'
brew 'jq'
brew 'lua'
brew 'luajit'
brew 'mas'
brew 'mercurial'
brew 'msmtp'
brew 'mtr'
brew 'nmap'
brew 'pandoc'
brew 's3cmd'
brew 'sloccount'
brew 'socat'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'watch'
brew 'weighttp'
brew 'wget'
brew 'xz'
brew 'youtube-dl'
brew 'whois'
brew 'bytemark-client'

cask 'bonjour-browser'
cask 'cask'
cask 'dayone-cli'
cask 'google-chrome'
cask 'mailmate'
cask 'sonos'
cask 'textmate'
cask 'tunnelblick'
cask 'vlc'

mas 'The Unarchiver', id: 425424353
mas 'Microsoft Remote Desktop', id: 715768417
mas 'Tweetbot', id: 557168941
mas 'Telegram', id: 747648890
mas 'Day One', id: 1055511498
